### ISSUE TITLE
Google Sheets conflict

### ISSUE THREAD

**Issue by richardstrong** [jswanner/DontF-WithPaste#114]
Copying & pasting is broken in Google Sheets when DFWP is enabled. Works again when it is disabled.

Using Chrome 96.0.4664.93

Note: would be nice if this were fixed, but the most useful change IMO would be extending the extension configuration to allow a blocklist instead of only an allowlist. That allows the user to leave the extension enabled and make exceptions in case of a conflict. Right now, I am forced to disable the extension everywhere just because of one conflict.

**Comment by jswanner** [comment]
I know everyone's internet browsing experience is very different from my own... That said, there's only a few sites that I need this extension to be "active" and the vast majority of sites I visit I very much **do not** want this extension active; GitHub & Google's applications are great examples of the latter.

Having this extension active by default and only disabling on sites where it causes problems means you would need to test disabling it on every site in order to determine if it should be disable or not, and that seems very backwards to me. With this extension inactive I can easily tell when a site is blocking paste, it then takes 2 mouse clicks to enable the extension for that site forevermore and then I can go about performing the paste action. I wouldn't want to always be wondering if this extension is causing problems I didn't know about. For instance, GitHub turns a file paste into a file upload, that is not a default browser action, that's GitHub doing something useful on `paste` events, if this extension were active while pasting a file then that file upload doesn't happen.

**Comment by fabform** [comment]
This is handy to find google sheets id
[find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by richardstrong** [comment]
Understood. I prefer it the other way and it works almost perfectly. I visit many many websites and this is the first time I've had a problem. So I don't think it would be unreasonable to offer both allow and block list logic, as e.g. ad blockers usually do.

**Comment by jswanner** [comment]
It's possible to create a rule/pattern that matches all except a known list. See: https://github.com/jswanner/DontFuckWithPaste/issues/55#issuecomment-372920606
