### ISSUE TITLE
google wont let me install the app without uploading my ID or giving them credit card info

### ISSUE THREAD

**Issue by charlesthomas** [jswanner/DontF-WithPaste#117]
i'm assuming it's because of the name, but google says it's "restricted content". it would be great if there was a way to install this without the chrome store, because i am not going to do either of those things

**Comment by jswanner** [comment]
Interesting, first I've heard of this... I've always had the "mature content" setting turned on due to the name and [Chrome's guidelines](https://developer.chrome.com/docs/webstore/rating/#strong-language). I suppose I can try to disable that setting and see what happens...

**Comment by plaurina** [comment]
I've used your plugin for my personal laptop for years, thank you.
For my work laptop, I have this issue (or similarly related issue). 

I'm forced into only being allowed to use my corporate account (managed by google) on Chrome/Brave. This account is managed by the corporation and does not include my birthday in my profile. Goole requests my birthday, but due to it being a managed account, they will not save the information - as it must be done through an admin at my corporation apparently. Of course, requesting access to "restricted content" or "mature content" items is frowned upon by most large corporation policies and often rejected solely on that designation.

<img width="1202" alt="Screen Shot 2022-05-05 at 10 27 39 AM" src="https://user-images.githubusercontent.com/1399502/166946270-51e58604-30ad-4fbf-8d1d-1478e7b5d2a1.png">

**Comment by gmejzej** [comment]
I am having the same problem. (I've used the extension for years and this is the first I've encountered this). I cannot gain access to the extension without signing into a Google Account. I figure it's got to the be the name.

Can you please change the name? Maybe Don't F$$$ with Paste? Whatever you want, just make it so we don't have to sign in to install it. It would be much appreciated.
