### ISSUE TITLE
Something funny going on with this website

### ISSUE THREAD

**Issue by vivekhub** [jswanner/DontF-WithPaste#134]
Hello:
 When I use DFWP on icicibank.com it used to work beautifully and their braindead JS code used to get disabled.  Now suddenly it stopped working. My JS-fu is not strong enough to debug this.  Can you please see what they are doing and handle it please?

Their website

https://infinity.icicibank.com/corp/AuthenticationController?FORMSGROUP_ID__=AuthenticationFG&__START_TRAN_FLAG__=Y&FG_BUTTONS__=LOAD&ACTION.LOAD=Y&AuthenticationFG.LOGIN_FLAG=1&BANK_ID=ICI&ITM=nli_personalb_personal_login_btn

**Comment by jswanner** [comment]
@vivekhub, that page actually has 2 password input fields depending on if viewing the password value is on or off. When viewing the password value is turn on then you are able to paste into the password field with the help of this extension; but when viewing the password value is off then pasting using this extension doesn't really help. And that's because in the second case, there's an extra `input` event listen that's interfering, and this extension does not circumvent that kind of interference.

This extension circumvents the most straight-forward approaches a website author can take to prevent copy, cut, and paste functionality. This extension does not try to circumvent all means by which a website author can take to prevent that functionality, partly because there are so many ways in which a website author can try to prevent those actions but also because this extension could end up causing more harm to your browsing experience if it did try to circumvent all the possible ways.

I think using something like [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en) would be a better way to get around what they are doing in the second case above. Luckily, if you toggle viewing of the password then you are able to paste into the field.

**Comment by vivekindee** [comment]
Thank you for the detailed response.  Much appreciated.
