### ISSUE TITLE
Way to include all websites

### ISSUE THREAD

**Issue by karthik53** [jswanner/DontF-WithPaste#137]
Is there a way to include all websites?
I tried adding /^https?:\/\/.*$/ but it didn't work
I have also observed that adding a website adds 2 entries every time, although not an issue for me.

**Comment by jswanner** [comment]
I don't recommend it, it'll cause other issues. See https://github.com/jswanner/DontF-WithPaste/issues/88

**Comment by karthik53** [comment]
Thanks for your response. Appreciate it.

**Comment by Jvst-Vitalik** [comment]
@jswanner I don't want to seem like an abuser or someone who is bypassing the rules. But could you, please, take a look at this website and tell me why your extension is not working?
(submithub.com)

I tried removing the "/" before the dots, uninstalling and reinstalling the extension, completely clearing the cache on my computer, restarting the computer, and trying with a different profile.

I'm using Windows 10 and the Google Chrome browser with the latest version available.

p.s. your extension worked today, but after I tried to "reconnect" the NordVPN, because the internet speed was a little bit low, it stopped working completely right away. None of the methods above helped me :(

**Comment by jswanner** [comment]
@Jvst-Vitalik, can you link to a page where it's not working? I'm not finding what you are describing

**Comment by Jvst-Vitalik** [comment]
> @Jvst-Vitalik, can you link to a page where it's not working? I'm not finding what you are describing

There’s a bit of a complicated system. You need to have a curator account to receive so-called paid submissions from artists, and only then will you have the opportunity to check whether it works on your side or not.

Is there any way I can send a screen-recorded video, or screenshots, or a piece of code from DevTools in a private message?
I’m a bit worried, to be honest. I don’t want to get banned, since the discussion/issue is in public, haha

I will be incredibly grateful for your help. If the problem gets solved, just send a link to a charity donation 🙏
